uvmf:
  environments:
    block_2:
      agents:
      - initiator_responder: INITIATOR
        name: spi_master
        type: spi_m
      - initiator_responder: RESPONDER
        name: wb_slave
        type: wb_s
      analysis_components:
      - name: block_2_pred
        parameters: []
        type: block_2_predictor
      - name: block_2_sb
        parameters: []
        type: block_2_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: spi_master.monitored_ap
        name: spi_master_ap
        trans_type: spi_m_transaction
      - connected_to: wb_slave.monitored_ap
        name: wb_slave_ap
        trans_type: wb_s_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_scoreboard
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: spi_master.monitored_ap
        receiver: block_2_pred.spi_ae
        validate: 'True'
      - driver: wb_slave.monitored_ap
        receiver: block_2_sb.wb_ae
        validate: 'True'
      - driver: block_2_pred.pre_to_sco_ap
        receiver: block_2_sb.sco_from_pre_ae
        validate: 'True'
