uvmf:
  environments:
    subsys:
      agents: []
      analysis_components:
      - name: sub_pred
        parameters: []
        type: subsys_predictor
      - name: sub_sb
        parameters: []
        type: subsys_scoreboard
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: b1
        parameters: []
        type: block_1
      - name: b2
        parameters: []
        type: block_2
      tlm_connections:
      - driver: b1.apb_master_ap
        receiver: sub_pred.subsys_apb_ae
        validate: 'True'
      - driver: b1.axi_master1_ap
        receiver: sub_pred.subsys_axi_1_ae
        validate: 'True'
      - driver: b1.axi_master2_ap
        receiver: sub_pred.subsys_axi_2_ae
        validate: 'True'
      - driver: sub_pred.pred_to_sco_ap
        receiver: sub_sb.sco_from_pred_ae
        validate: 'True'
      - driver: b2.wb_slave_ap
        receiver: sub_sb.wb_s_ae
        validate: 'True'
