uvmf:
  environments:
    subsys:
      agents: []
      analysis_components:
      - name: sub_pred
        parameters: []
        type: subsys_predictor
      - name: sub_sb
        parameters: []
        type: subsys_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: b1.apb_master_ap
        name: block_1_ap1
        trans_type: apb_m_transaction
      - connected_to: b1.axi_master1_ap
        name: block_1_ap2
        trans_type: axi_m_transaction
      - connected_to: b1.axi_master2_ap
        name: block_1_ap3
        trans_type: axi_m_transaction
      - connected_to: b2.wb_slave_ap
        name: block_2_ap1
        trans_type: wb_s_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_scoreboard
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: apb_m_pkg
      - name: axi_m_pkg
      - name: wb_s_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: b1
        parameters: []
        type: block_1
      - name: b2
        parameters: []
        type: block_2
      tlm_connections:
      - driver: b1.apb_master_ap
        receiver: sub_pred.subsys_apb_ae
        validate: 'True'
      - driver: b1.axi_master1_ap
        receiver: sub_pred.subsys_axi_1_ae
        validate: 'True'
      - driver: b1.axi_master2_ap
        receiver: sub_pred.subsys_axi_2_ae
        validate: 'True'
      - driver: sub_pred.subsys_pre_to_sco_ap
        receiver: sub_sb.subsys_sco_from_pre_ae
        validate: 'True'
      - driver: b2.wb_slave_ap
        receiver: sub_sb.subsys_wb_ae
        validate: 'True'
