$UVMF_VIP_LIBRARY_HOME/interface_packages/wb_slave_pkg/src/wb_slave_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/wb_slave_pkg/src/wb_slave_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/wb_slave_pkg/src/wb_slave_driver_bfm.sv
