uvmf:
  environments:
    block_3:
      agents:
      - initiator_responder: INITIATOR
        name: wb_master
        type: wb_m
      - initiator_responder: RESPONDER
        name: axi_slave
        type: axi_s
      analysis_components:
      - name: block_3_pred
        parameters: []
        type: block_3_predictor
      - name: block_3_sb
        parameters: []
        type: block_3_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: wb_master.monitored_ap
        name: block_3_wb
        trans_type: wb_m_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_scoreboard
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: wb_master.monitored_ap
        receiver: block_3_pred.wb_ae
        validate: 'True'
      - driver: axi_slave.monitored_ap
        receiver: block_3_sb.axi_ae
        validate: 'True'
      - driver: block_3_pred.pre_to_sco_ap
        receiver: block_3_sb.sco_from_pre_ae
        validate: 'True'
