uvmf:
  environments:
    block_1:
      agents:
      - initiator_responder: INITIATOR
        name: apb_master
        type: apb_m
      - initiator_responder: INITIATOR
        name: axi_master1
        type: axi_m
      - initiator_responder: INITIATOR
        name: axi_master2
        type: axi_m
      - initiator_responder: RESPONDER
        name: spi_slave
        type: spi_s
      analysis_components:
      - name: block_1_pred
        parameters: []
        type: block_1_predictor
      - name: block_1_sb
        parameters: []
        type: block_1_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: apb_master.monitored_ap
        name: apb_master_ap
        trans_type: apb_m_transaction
      - connected_to: axi_master1.monitored_ap
        name: axi_master1_ap
        trans_type: axi_m_transaction
      - connected_to: axi_master2.monitored_ap
        name: axi_master2_ap
        trans_type: axi_m_transaction
      - connected_to: spi_slave.monitored_ap
        name: spi_slave_ap
        trans_type: spi_s_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_scoreboard
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: spi_slave.monitored_ap
        receiver: block_1_sb.spi_ae
        validate: 'True'
      - driver: apb_master.monitored_ap
        receiver: block_1_pred.apb_ae
        validate: 'True'
      - driver: axi_master1.monitored_ap
        receiver: block_1_pred.axi_1_ae
        validate: 'True'
      - driver: axi_master2.monitored_ap
        receiver: block_1_pred.axi_2_ae
        validate: 'True'
      - driver: block_1_pred.pre_to_sco_ap
        receiver: block_1_sb.sco_from_pre_ae
        validate: 'True'
