$UVMF_VIP_LIBRARY_HOME/interface_packages/mem_pkg/src/mem_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/mem_pkg/src/mem_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/mem_pkg/src/mem_driver_bfm.sv
