uvmf:
  environments:
    jtag:
      agents:
      - initiator_responder: INITIATOR
        name: jtag_in
        type: jtag
      - initiator_responder: RESPONDER
        name: jtag_out
        type: jtag
      analysis_components:
      - name: jtag_pred
        parameters: []
        type: jtag_predictor
      - name: jtag_cov
        parameters: []
        type: jtag_coverage
      analysis_exports: []
      analysis_ports:
      - connected_to: jtag_in.monitored_ap
        name: jtag_in_ap
        trans_type: jtag_transaction
      - connected_to: jtag_out.monitored_ap
        name: jtag_out_ap
        trans_type: jtag_transaction
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: jtag_sb
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: jtag_transaction
      subenvs: []
      tlm_connections:
      - driver: jtag_in.monitored_ap
        receiver: jtag_pred.jtag_in_ae
        validate: 'True'
      - driver: jtag_pred.jtag_sb_ap
        receiver: jtag_sb.expected_analysis_export
        validate: 'True'
      - driver: jtag_out.monitored_ap
        receiver: jtag_sb.actual_analysis_export
        validate: 'True'
      - driver: jtag_in.monitored_ap
        receiver: jtag_cov.jtag_cov_ae
        validate: 'True'
