uvmf:
  environments:
    block_3:
      agents:
      - initiator_responder: INITIATOR
        name: wishbone_master_agent
        type: wishbone_master
      - initiator_responder: RESPONDER
        name: axi_slave_agent
        type: axi_slave
      analysis_components:
      - name: block_3_pred
        parameters: []
        type: block_3_predictor
      - name: block_3_sb
        parameters: []
        type: block_3_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: axi_slave_agent.monitored_ap
        name: axi_slave_ap
        trans_type: axi_slave_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'True'
        name: block_3_cfgVar1
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: wishbone_master_agent.monitored_ap
        receiver: block_3_pred.wishbone_master_agent_ae
        validate: 'True'
      - driver: block_3_pred.block_3_sb_ap
        receiver: block_3_sb.axi_slave_pred_sb_ae
        validate: 'True'
      - driver: axi_slave_agent.monitored_ap
        receiver: block_3_sb.axi_slave_agent_sb_ae
        validate: 'True'
