uvmf:
  environments:
    system:
      agents: []
      analysis_components: []
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: s1
        parameters: []
        type: subsys
      - name: b3
        parameters: []
        type: block_3
      tlm_connections: []
