uvmf:
  environments:
    system:
      agents: []
      analysis_components:
      - name: sys_pred
        parameters: []
        type: sys_predictor
      - name: sys_sb
        parameters: []
        type: sys_scoreboard
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'False'
        name: has_scoreboard
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: s1
        parameters: []
        type: subsys
      - name: b3
        parameters: []
        type: block_3
      tlm_connections:
      - driver: s1.block_1_ap1
        receiver: sys_pred.sys_apb_ae
        validate: 'True'
      - driver: s1.block_1_ap2
        receiver: sys_pred.sys_axi_1_ae
        validate: 'True'
      - driver: s1.block_1_ap3
        receiver: sys_pred.sys_axi_2_ae
        validate: 'True'
      - driver: sys_pred.sys_pre_to_sco_ap
        receiver: sys_sb.sys_sco_from_pre_ae
        validate: 'True'
      - driver: b3.axi_slave_ap
        receiver: sys_sb.sys_axi_ae
        validate: 'True'
