uvmf:
  environments:
    add:
      agents:
      - initiator_responder: INITIATOR
        name: add_in_agent
        type: add_in
      - initiator_responder: RESPONDER
        name: add_out_agent
        type: add_out
      analysis_components:
      - name: add_pred
        parameters: []
        type: add_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: add_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: add_out_transaction
      subenvs: []
      tlm_connections:
      - driver: add_in_agent.monitored_ap
        receiver: add_pred.add_in_agent_ae
        validate: 'True'
      - driver: add_pred.add_sb_ap
        receiver: add_sb.expected_analysis_export
        validate: 'True'
      - driver: add_out_agent.monitored_ap
        receiver: add_sb.actual_analysis_export
        validate: 'True'
