$UVMF_VIP_LIBRARY_HOME/interface_packages/jtag_b_pkg/src/jtag_b_if.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/jtag_b_pkg/src/jtag_b_monitor_bfm.sv
$UVMF_VIP_LIBRARY_HOME/interface_packages/jtag_b_pkg/src/jtag_b_driver_bfm.sv
