uvmf:
  environments:
    add:
      agents:
      - initiator_responder: INITIATOR
        name: add_in_agent
        type: add_in
      - initiator_responder: RESPONDER
        name: add_out_agent
        type: add_out
      analysis_components:
      - name: add_pred
        parameters: []
        type: add_predictor
      - name: add_sb
        parameters: []
        type: add_scoreboard
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'True'
        name: cfg_var
        type: bit
        value: 1'b1
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: add_in_agent.monitored_ap
        receiver: add_pred.add_in_agent_ae
        validate: 'True'
      - driver: add_pred.add_sb_ap
        receiver: add_sb.add_out_pred_sb_ae
        validate: 'True'
      - driver: add_out_agent.monitored_ap
        receiver: add_sb.add_out_ag_sb_ae
        validate: 'True'
