uvmf:
  environments:
    block_2:
      agents:
      - initiator_responder: INITIATOR
        name: spi_master_agent
        type: spi_master
      - initiator_responder: RESPONDER
        name: wishbone_slave_agent
        type: wishbone_slave
      analysis_components:
      - name: block_2_pred
        parameters: []
        type: block_2_predictor
      - name: block_2_sb
        parameters: []
        type: block_2_scoreboard
      analysis_exports: []
      analysis_ports:
      - connected_to: wishbone_slave_agent.monitored_ap
        name: wishbone_ap
        trans_type: wishbone_slave_transaction
      config_constraints: []
      config_vars:
      - comment: ''
        isrand: 'True'
        name: block_2_cfgVar1
        type: bit
        value: ''
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: spi_master_agent.monitored_ap
        receiver: block_2_pred.spi_master_agent_ae
        validate: 'True'
      - driver: block_2_pred.block_2_sb_ap
        receiver: block_2_sb.wishbone_slave_pred_sb_ae
        validate: 'True'
      - driver: wishbone_slave_agent.monitored_ap
        receiver: block_2_sb.wishbone_slave_agent_sb_ae
        validate: 'True'
