uvmf:
  environments:
    jtag:
      agents:
      - initiator_responder: INITIATOR
        name: jtag_agent_a
        type: jtag_a
      - initiator_responder: INITIATOR
        name: jtag_agent_b
        type: jtag_b
      analysis_components:
      - name: jtag_pred
        parameters: []
        type: jtag_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: jtag_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: jtag_a_transaction
      subenvs: []
      tlm_connections:
      - driver: jtag_agent_b.monitored_ap
        receiver: jtag_pred.jtag_agent_b_ae
        validate: 'True'
      - driver: jtag_pred.jtag_sb_ap
        receiver: jtag_sb.expected_analysis_export
        validate: 'True'
      - driver: jtag_agent_a.monitored_ap
        receiver: jtag_sb.actual_analysis_export
        validate: 'True'
