uvmf:
  environments:
    block_c:
      agents:
      - initiator_responder: INITIATOR
        name: mem_in
        type: mem
      - initiator_responder: INITIATOR
        name: mem_out
        type: mem
      - initiator_responder: INITIATOR
        name: pkt_out
        type: pkt
      analysis_components:
      - name: blk_c_pred
        parameters: []
        type: block_c_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: mvc_pkg
      - name: mgc_pcie_v2_0_pkg
      - name: mgc_axi4_v1_0_pkg
      - name: mgc_apb3_v1_0_pkg
      non_uvmf_components: []
      parameters: []
      qvip_connections:
      - ap_key: trans_ap
        driver: qvip_env_axi4_master_0
        receiver: blk_c_pred.axi4_master_0_ae
        validate: 'True'
      - ap_key: trans_ap
        driver: qvip_env_axi4_master_1
        receiver: blk_c_pred.axi4_master_1_ae
        validate: 'True'
      - ap_key: trans_ap
        driver: qvip_env_axi4_slave
        receiver: axi4_slave_sb.actual_analysis_export
        validate: 'True'
      - ap_key: trans_ap
        driver: qvip_env_apb3_config_master
        receiver: apb3_cfg_sb.actual_analysis_export
        validate: 'True'
      qvip_memory_agents: []
      qvip_subenvs:
      - name: qvip_env
        type: qvip_agents
      scoreboards:
      - name: mem_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: mem_transaction
      - name: pkt_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: pkt_transaction
      - name: axi4_slave_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: mvc_sequence_item_base
      - name: apb3_cfg_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: mvc_sequence_item_base
      subenvs: []
      tlm_connections:
      - driver: mem_in.monitored_ap
        receiver: blk_c_pred.mem_in_ae
        validate: 'True'
      - driver: blk_c_pred.mem_sb_ap
        receiver: mem_sb.expected_analysis_export
        validate: 'True'
      - driver: blk_c_pred.pkt_sb_ap
        receiver: pkt_sb.expected_analysis_export
        validate: 'True'
      - driver: blk_c_pred.axi4_slave_ap
        receiver: axi4_slave_sb.expected_analysis_export
        validate: 'True'
      - driver: blk_c_pred.apb3_config_master_ap
        receiver: apb3_cfg_sb.expected_analysis_export
        validate: 'True'
      - driver: mem_out.monitored_ap
        receiver: mem_sb.actual_analysis_export
        validate: 'True'
      - driver: pkt_out.monitored_ap
        receiver: pkt_sb.actual_analysis_export
        validate: 'True'
